# Generated by Django 4.0.3 on 2022-03-29 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_customer_delete_customerregister'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='UserProfile',
        ),
    ]
