# Generated by Django 4.0.3 on 2022-03-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
