# Generated by Django 4.0.3 on 2022-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.FileField(blank=True, default='/property-1.jpg', null=True, upload_to='media'),
        ),
    ]
