# Generated by Django 4.0.3 on 2022-03-28 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_img', models.ImageField(max_length=255, upload_to='')),
                ('prop_area', models.CharField(max_length=255)),
                ('prop_price', models.IntegerField(max_length=255)),
                ('prop_description', models.CharField(max_length=255)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_contact', models.IntegerField()),
                ('agent_about', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
