# Generated by Django 4.0.3 on 2022-03-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_user_alter_property_prop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent_contact',
            field=models.CharField(max_length=12),
        ),
    ]
