# Generated by Django 3.2 on 2022-03-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_prop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent_email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
