# Generated by Django 4.0.3 on 2022-03-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_property_agent_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent_about',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='agent_contact',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='agent_email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='agent_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='prop_area',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='prop_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='prop_img',
            field=models.ImageField(default=1, max_length=255, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='prop_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='prop_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='prop_status',
            field=models.CharField(choices=[('1', 'Naveen'), ('2', 'Pranav'), ('3', 'Isha'), ('4', 'Saloni')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
