# Generated by Django 4.0.3 on 2022-03-29 03:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_agent_about_property_agent_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='prop_status',
        ),
        migrations.AddField(
            model_name='property',
            name='doc_listed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('permit_num', 'Work Permit'), ('passport_num', 'Passport')], default=False, max_length=23, verbose_name='Documents Received?'),
        ),
    ]
