# Generated by Django 4.0.3 on 2022-03-29 03:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_prop_status_property_doc_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='doc_listed',
        ),
        migrations.AddField(
            model_name='property',
            name='prop_State',
            field=models.CharField(choices=[('Select', 'Select'), ('Assam', 'Assam'), ('Maharashtra', 'Maharashtra'), ('Madhya_Pradesh', 'Madhya Pradesh'), ('West_Bengal', 'West Bengal')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('For_Sale', 'For Sale'), ('Not_Available', 'Not Available'), ('Sold', 'Sold')], default=False, max_length=27, verbose_name='Documents Received?'),
        ),
    ]
