# Generated by Django 4.0.3 on 2022-03-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_property_prop_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_State',
            field=models.CharField(blank=True, choices=[('Select State', 'Select State'), ('Assam', 'Assam'), ('Maharashtra', 'Maharashtra'), ('Madhya_Pradesh', 'Madhya Pradesh'), ('West_Bengal', 'West Bengal')], max_length=20, null=True),
        ),
    ]
