# Generated by Django 4.0.3 on 2022-03-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_property_prop_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_State',
            field=models.CharField(choices=[('Select_State', 'Select State'), ('Assam', 'Assam'), ('Maharashtra', 'Maharashtra'), ('Madhya_Pradesh', 'Madhya Pradesh'), ('West_Bengal', 'West Bengal')], default='Select_State', max_length=20),
        ),
    ]
