# Generated by Django 4.0.3 on 2022-03-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_property_prop_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='prop_State',
            new_name='prop_state',
        ),
    ]
