# Generated by Django 4.0.3 on 2022-03-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_property_prop_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_state',
            field=models.CharField(blank=True, choices=[('select_state', 'Select State'), ('Assam', 'Assam'), ('Maharashtra', 'Maharashtra'), ('Madhya_Pradesh', 'Madhya Pradesh'), ('West_Bengal', 'West Bengal')], default=None, max_length=80, null=True),
        ),
    ]
