# Generated by Django 4.0.3 on 2022-03-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_alter_property_prop_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='prop_state',
        ),
    ]
