# Generated by Django 4.0.3 on 2022-03-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_remove_property_prop_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prop_state',
            field=models.CharField(choices=[('select_state', 'Select State'), ('Assam', 'Assam'), ('Maharashtra', 'Maharashtra'), ('Madhya_Pradesh', 'Madhya Pradesh'), ('West_Bengal', 'West Bengal')], default=0, max_length=80),
            preserve_default=False,
        ),
    ]
