# Generated by Django 4.0.3 on 2022-03-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_property_prop_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_state',
            field=models.CharField(choices=[('Assam', 'Assam'), ('Maharashtra', 'Maharashtra'), ('Madhya_Pradesh', 'Madhya Pradesh'), ('West_Bengal', 'West Bengal')], max_length=80),
        ),
    ]
