# Generated by Django 4.0.3 on 2022-03-29 04:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_property_prop_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('For_Sale', 'For Sale'), ('Not_Available', 'Not Available'), ('Sold', 'Sold')], default=False, max_length=27, verbose_name='Status'),
        ),
    ]
