# Generated by Django 4.0.3 on 2022-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_property_prop_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prop_city',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Ujjain', 'Ujjain'), ('Indore', 'Indore')], default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Madhya_Pradesh', 'Madhya Pradesh')], max_length=80),
        ),
    ]
