# Generated by Django 4.0.3 on 2022-03-30 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 14, 37, 43, 105412)),
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='requirement_type',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='requirement_type',
            field=models.ManyToManyField(choices=[('Maharashtra', 'Maharashtra'), ('Madhya_Pradesh', 'Madhya Pradesh')], max_length=111, related_name='test', to='property.property'),
        ),
    ]
