# Generated by Django 4.0.3 on 2022-03-30 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_alter_enquiry_date_of_inquiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='requirement_type',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 14, 41, 21, 520034)),
        ),
    ]
