# Generated by Django 4.0.3 on 2022-03-30 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_alter_enquiry_date_of_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='prop_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PropertyRelation', to='property.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 14, 45, 33, 776828)),
        ),
    ]
