# Generated by Django 4.0.3 on 2022-03-30 09:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0031_enquiry_prop_table_alter_enquiry_date_of_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='prop_table',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 14, 48, 51, 824583)),
        ),
    ]
