# Generated by Django 4.0.3 on 2022-03-30 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_remove_enquiry_prop_table_enquiry_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 14, 50, 6, 874372)),
        ),
    ]
