# Generated by Django 4.0.3 on 2022-03-30 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_user_img'),
        ('property', '0037_enquiry_prop_table_alter_enquiry_date_of_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='user',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 16, 34, 38, 18319)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='prop_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropertyRelation', to='user_profile.userprofile'),
        ),
    ]
