# Generated by Django 4.0.3 on 2022-03-30 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0039_alter_enquiry_date_of_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='prop_table',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 16, 35, 19, 374158)),
        ),
    ]
