# Generated by Django 4.0.3 on 2022-03-30 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_remove_enquiry_prop_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 16, 37, 19, 342152)),
        ),
    ]
