# Generated by Django 4.0.3 on 2022-03-30 11:48

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0042_alter_enquiry_date_of_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='duration',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1_Month', '1 Month'), ('3_Month', '3 Month'), ('1_Year', '1 Year'), ('Not_Sure_how_long', 'Not Sure How Long')], default=False, max_length=40, verbose_name='Duration of Stay'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 17, 18, 47, 538722)),
        ),
    ]
