# Generated by Django 4.0.3 on 2022-03-30 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0043_enquiry_duration_alter_enquiry_date_of_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Gender',
            new_name='requirement_type',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 17, 31, 35, 308834)),
        ),
    ]
