# Generated by Django 4.0.3 on 2022-03-30 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0045_remove_enquiry_userprofile_enquiry_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='user',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 17, 43, 2, 322124)),
        ),
    ]
