# Generated by Django 4.0.3 on 2022-03-30 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0047_alter_enquiry_date_of_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='current_user',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 17, 45, 13, 798667)),
        ),
    ]
