# Generated by Django 4.0.3 on 2022-03-30 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0048_enquiry_current_user_alter_enquiry_date_of_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='current_user',
            field=models.CharField(default='123', max_length=5),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 18, 29, 46, 942798)),
        ),
    ]
