# Generated by Django 4.0.3 on 2022-03-30 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0049_alter_enquiry_current_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 18, 29, 57, 269507)),
        ),
    ]
