# Generated by Django 4.0.3 on 2022-03-30 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0050_alter_enquiry_date_of_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='current_user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 18, 35, 43, 607497)),
        ),
    ]
