# Generated by Django 4.0.3 on 2022-03-30 13:34

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0051_rename_current_user_enquiry_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 19, 4, 33, 830595)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='duration',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1_Month', '1 Month'), ('3_Month', '3 Month'), ('1_Year', '1 Year'), ('Not_Sure_how_long', 'Not Sure How Long')], default=None, max_length=40, verbose_name='Duration of Stay'),
        ),
    ]
