# Generated by Django 4.0.3 on 2022-03-30 13:37

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0052_alter_enquiry_date_of_inquiry_alter_enquiry_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='property_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Raw Land', 'Raw Land'), ('Lot in a Development', 'Lot in a Development'), ('Single Family Home', 'Single Family Home'), ('Other', 'Other')], default=None, max_length=54, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 19, 7, 55, 936763)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='duration',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1 Month', '1 Month'), ('3 Month', '3 Month'), ('1 Year', '1 Year'), ('Not Sure how long', 'Not Sure How Long')], default=None, max_length=40, verbose_name='Duration of Stay'),
        ),
    ]
