# Generated by Django 4.0.3 on 2022-03-30 13:44

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0053_enquiry_property_type_alter_enquiry_date_of_inquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Budget',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0 - 50k', '0 - 50k'), ('50k - 5L', '50k - 5L'), ('5L-15L', '5L-15L'), ('15L - 1Cr', '15 L - 1Cr')], default=None, max_length=33, verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('In Town', 'In Town'), ('Farm or Ranch', 'Farm or Ranch'), ('Ocean View', 'Ocean View'), ('Beachfront', 'Beachfront'), ('Other', 'Other')], default=None, max_length=49, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='questions',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 19, 14, 56, 311221)),
        ),
    ]
