# Generated by Django 4.0.3 on 2022-03-30 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0054_enquiry_budget_enquiry_location_enquiry_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='user_name',
            field=models.CharField(default='123', max_length=5),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_inquiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 21, 0, 51, 881112)),
        ),
    ]
